const favicon = (domain: string) =>
  `https://t0.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://${domain}&size=128`;

export const schools = [
  { name: "Stanford University", logo: favicon("stanford.edu") },
  { name: "University of Florida", logo: favicon("ufl.edu") },
  { name: "UCLA", logo: favicon("ucla.edu") },
  { name: "Princeton University", logo: favicon("princeton.edu") },
  { name: "Harvard University", logo: favicon("harvard.edu") },
  { name: "University of Michigan", logo: favicon("umich.edu") },
  { name: "University of North Carolina", logo: favicon("unc.edu") },
  { name: "UC Berkeley", logo: favicon("berkeley.edu") },
  { name: "Duke University", logo: favicon("duke.edu") },
  { name: "Yale University", logo: favicon("yale.edu") },
  { name: "Columbia University", logo: favicon("columbia.edu") },
  { name: "University of Pennsylvania", logo: favicon("upenn.edu") },
  { name: "University of Virginia", logo: favicon("virginia.edu") },
  { name: "University of Notre Dame", logo: favicon("nd.edu") },
  { name: "University of Texas", logo: favicon("utexas.edu") },
  { name: "Vanderbilt University", logo: favicon("vanderbilt.edu") },
  { name: "University of Georgia", logo: favicon("uga.edu") },
  { name: "Ohio State University", logo: favicon("osu.edu") },
  { name: "Florida State University", logo: favicon("fsu.edu") },
  { name: "Georgia Tech", logo: favicon("gatech.edu") },
  { name: "USC", logo: favicon("usc.edu") },
  { name: "University of Wisconsin", logo: favicon("wisc.edu") },
  { name: "Northwestern University", logo: favicon("northwestern.edu") },
  { name: "Georgetown University", logo: favicon("georgetown.edu") },
  { name: "Clemson University", logo: favicon("clemson.edu") },
  { name: "Brown University", logo: favicon("brown.edu") },
  { name: "University of Washington", logo: favicon("washington.edu") },
  { name: "NC State", logo: favicon("ncsu.edu") },
  { name: "Michigan State University", logo: favicon("msu.edu") },
  { name: "Purdue University", logo: favicon("purdue.edu") },
  { name: "Texas A&M", logo: favicon("tamu.edu") },
  { name: "University of Maryland", logo: favicon("umd.edu") },
  { name: "Cornell University", logo: favicon("cornell.edu") },
  { name: "Virginia Tech", logo: favicon("vt.edu") },
  { name: "Wake Forest University", logo: favicon("wfu.edu") },
  { name: "UC Santa Barbara", logo: favicon("ucsb.edu") },
  { name: "UC San Diego", logo: favicon("ucsd.edu") },
  { name: "University of Miami", logo: favicon("miami.edu") },
  { name: "Boston College", logo: favicon("bc.edu") },
  { name: "University of Illinois", logo: favicon("illinois.edu") },
  { name: "Indiana University", logo: favicon("indiana.edu") },
  { name: "Dartmouth College", logo: favicon("dartmouth.edu") },
  { name: "Rice University", logo: favicon("rice.edu") },
  { name: "Auburn University", logo: favicon("auburn.edu") },
  { name: "University of Minnesota", logo: favicon("umn.edu") },
  { name: "UC Davis", logo: favicon("ucdavis.edu") },
  { name: "University of South Florida", logo: favicon("usf.edu") },
  { name: "UC Irvine", logo: favicon("uci.edu") },
  { name: "Villanova University", logo: favicon("villanova.edu") },
  { name: "University of Pittsburgh", logo: favicon("pitt.edu") },
  { name: "Boston University", logo: favicon("bu.edu") },
  { name: "Syracuse University", logo: favicon("syracuse.edu") },
  { name: "UMass Amherst", logo: favicon("umass.edu") },
  { name: "UCF", logo: favicon("ucf.edu") },
  { name: "University of Oregon", logo: favicon("uoregon.edu") },
  { name: "Baylor University", logo: favicon("baylor.edu") },
  { name: "Penn State", logo: favicon("psu.edu") },
  { name: "University of South Carolina", logo: favicon("sc.edu") },
  { name: "William & Mary", logo: favicon("wm.edu") },
  { name: "UConn", logo: favicon("uconn.edu") },
  { name: "San Diego State", logo: favicon("sdsu.edu") },
  { name: "Rutgers University", logo: favicon("rutgers.edu") },
  { name: "University of Oklahoma", logo: favicon("ou.edu") },
  { name: "University of Tennessee", logo: favicon("utk.edu") },
  { name: "University of Iowa", logo: favicon("uiowa.edu") },
  { name: "Arizona State University", logo: favicon("asu.edu") },
  { name: "TCU", logo: favicon("tcu.edu") },
  { name: "University of Alabama", logo: favicon("ua.edu") },
  { name: "Davidson College", logo: favicon("davidson.edu") },
  { name: "University of Arizona", logo: favicon("arizona.edu") },
  { name: "University of Kentucky", logo: favicon("uky.edu") },
  { name: "LSU", logo: favicon("lsu.edu") },
  { name: "Iowa State University", logo: favicon("iastate.edu") },
  { name: "University of Missouri", logo: favicon("missouri.edu") },
  { name: "University of Richmond", logo: favicon("richmond.edu") },
  { name: "University of San Diego", logo: favicon("sandiego.edu") },
  { name: "James Madison University", logo: favicon("jmu.edu") },
  { name: "Gonzaga University", logo: favicon("gonzaga.edu") },
  { name: "Ole Miss", logo: favicon("olemiss.edu") },
  { name: "University of Utah", logo: favicon("utah.edu") },
  { name: "Northeastern University", logo: favicon("northeastern.edu") },
  { name: "CU Boulder", logo: favicon("colorado.edu") },
  { name: "University of St Thomas", logo: favicon("stthomas.edu") },
  { name: "Naval Academy", logo: favicon("usna.edu") },
  { name: "CSU Long Beach", logo: favicon("csulb.edu") },
  { name: "Air Force Academy", logo: favicon("usafa.edu") },
  { name: "Oregon State University", logo: favicon("oregonstate.edu") },
  { name: "Miami University", logo: favicon("miamioh.edu") },
  { name: "Lehigh University", logo: favicon("lehigh.edu") },
  { name: "FIU", logo: favicon("fiu.edu") },
  { name: "University of Cincinnati", logo: favicon("uc.edu") },
  { name: "BYU", logo: favicon("byu.edu") },
  { name: "University of Arkansas", logo: favicon("uark.edu") },
  { name: "Oklahoma State", logo: favicon("okstate.edu") },
  { name: "University of Kansas", logo: favicon("ku.edu") },
  { name: "Elon University", logo: favicon("elon.edu") },
  { name: "Pepperdine University", logo: favicon("pepperdine.edu") },
  { name: "SMU", logo: favicon("smu.edu") },
  { name: "University of Delaware", logo: favicon("udel.edu") },
  { name: "University of Louisville", logo: favicon("louisville.edu") },
  { name: "University of San Francisco", logo: favicon("usfca.edu") },
];
