const espn = (id: number) =>
  `https://a.espncdn.com/i/teamlogos/ncaa/500/${id}.png`;

export const schools = [
  { name: "Stanford University", logo: espn(24) },
  { name: "University of Florida", logo: espn(57) },
  { name: "UCLA", logo: espn(26) },
  { name: "Princeton University", logo: espn(163) },
  { name: "Harvard University", logo: espn(108) },
  { name: "University of Michigan", logo: espn(130) },
  { name: "University of North Carolina", logo: espn(153) },
  { name: "UC Berkeley", logo: espn(25) },
  { name: "Duke University", logo: espn(150) },
  { name: "Yale University", logo: espn(43) },
  { name: "Columbia University", logo: espn(171) },
  { name: "University of Pennsylvania", logo: espn(219) },
  { name: "University of Virginia", logo: espn(258) },
  { name: "University of Notre Dame", logo: espn(87) },
  { name: "University of Texas", logo: espn(251) },
  { name: "Vanderbilt University", logo: espn(238) },
  { name: "University of Georgia", logo: espn(61) },
  { name: "Ohio State University", logo: espn(194) },
  { name: "Florida State University", logo: espn(52) },
  { name: "Georgia Tech", logo: espn(59) },
  { name: "USC", logo: espn(30) },
  { name: "University of Wisconsin", logo: espn(275) },
  { name: "Northwestern University", logo: espn(77) },
  { name: "Georgetown University", logo: espn(46) },
  { name: "Clemson University", logo: espn(228) },
  { name: "Brown University", logo: espn(225) },
  { name: "University of Washington", logo: espn(264) },
  { name: "NC State", logo: espn(152) },
  { name: "Michigan State University", logo: espn(127) },
  { name: "Purdue University", logo: espn(2509) },
  { name: "Texas A&M", logo: espn(245) },
  { name: "University of Maryland", logo: espn(120) },
  { name: "Cornell University", logo: espn(172) },
  { name: "Virginia Tech", logo: espn(259) },
  { name: "Wake Forest University", logo: espn(154) },
  { name: "UC Santa Barbara", logo: espn(2540) },
  { name: "UC San Diego", logo: espn(28) },
  { name: "University of Miami", logo: espn(2390) },
  { name: "Boston College", logo: espn(103) },
  { name: "University of Illinois", logo: espn(356) },
  { name: "Indiana University", logo: espn(84) },
  { name: "Dartmouth College", logo: espn(159) },
  { name: "Rice University", logo: espn(242) },
  { name: "Auburn University", logo: espn(2) },
  { name: "University of Minnesota", logo: espn(135) },
  { name: "UC Davis", logo: espn(302) },
  { name: "University of South Florida", logo: espn(58) },
  { name: "UC Irvine", logo: espn(300) },
  { name: "Villanova University", logo: espn(222) },
  { name: "University of Pittsburgh", logo: espn(221) },
  { name: "Boston University", logo: espn(104) },
  { name: "Syracuse University", logo: espn(183) },
  { name: "UMass Amherst", logo: espn(113) },
  { name: "UCF", logo: espn(2116) },
  { name: "University of Oregon", logo: espn(2483) },
  { name: "Baylor University", logo: espn(239) },
  { name: "Penn State", logo: espn(213) },
  { name: "University of South Carolina", logo: espn(2579) },
  { name: "William & Mary", logo: espn(2729) },
  { name: "UConn", logo: espn(41) },
  { name: "San Diego State", logo: espn(21) },
  { name: "Rutgers University", logo: espn(164) },
  { name: "University of Oklahoma", logo: espn(201) },
  { name: "University of Tennessee", logo: espn(2633) },
  { name: "University of Iowa", logo: espn(2294) },
  { name: "Arizona State University", logo: espn(9) },
  { name: "TCU", logo: espn(2628) },
  { name: "University of Alabama", logo: espn(333) },
  { name: "Davidson College", logo: espn(2166) },
  { name: "University of Arizona", logo: espn(12) },
  { name: "University of Kentucky", logo: espn(96) },
  { name: "LSU", logo: espn(99) },
  { name: "Iowa State University", logo: espn(66) },
  { name: "University of Missouri", logo: espn(142) },
  { name: "University of Richmond", logo: espn(257) },
  { name: "University of San Diego", logo: espn(301) },
  { name: "James Madison University", logo: espn(256) },
  { name: "Gonzaga University", logo: espn(2250) },
  { name: "Ole Miss", logo: espn(145) },
  { name: "University of Utah", logo: espn(254) },
  { name: "Northeastern University", logo: espn(111) },
  { name: "CU Boulder", logo: espn(38) },
  { name: "University of St Thomas", logo: espn(2900) },
  { name: "Naval Academy", logo: espn(2426) },
  { name: "CSU Long Beach", logo: espn(299) },
  { name: "Air Force Academy", logo: espn(2005) },
  { name: "Oregon State University", logo: espn(204) },
  { name: "Miami University", logo: espn(193) },
  { name: "Lehigh University", logo: espn(2329) },
  { name: "FIU", logo: espn(2229) },
  { name: "University of Cincinnati", logo: espn(2132) },
  { name: "BYU", logo: espn(252) },
  { name: "University of Arkansas", logo: espn(8) },
  { name: "Oklahoma State", logo: espn(197) },
  { name: "University of Kansas", logo: espn(2305) },
  { name: "Elon University", logo: espn(2210) },
  { name: "Pepperdine University", logo: espn(2492) },
  { name: "SMU", logo: espn(2567) },
  { name: "University of Delaware", logo: espn(48) },
  { name: "University of Louisville", logo: espn(97) },
  { name: "University of San Francisco", logo: espn(2539) },
];
